### ISSUE TITLE
Update FTP Summary stats script to account for BoW submissions

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-utils#20]
The "FTP summary stats script" [1] needs to be updated to account for submissions from the Depo app that are from a "Body of Work" so that any summary stats for these submissions can be moved to the public FTP directory.

[1] https://github.com/EBISPOT/gwas-utils/tree/master/ftpSummaryStatsScript

**Comment by twhetzel** [comment]
@jdhayhurst is this update released?

**Comment by jdhayhurst** [comment]
Partially complete - but needs revising to handle BoW submissions that then receive pmids

**Comment by jdhayhurst** [comment]
Need to tie to the data release. Separate script that runs after the data release checking for anything that was named only GCST on the ftp but is now present in the STUDY table in the db and create symlink based on the author_pmid_gcst convention.

**Comment by jdhayhurst** [comment]
Need to review FTP storage structure (keep below 5000 items?) - what kind of structure can we add? pmid? GCP?

**Comment by jdhayhurst** [comment]
we might be able to maintain the paths over http using a .htaccess file with redirects mapping our desired URLs to the correct path on the FTP.

**Comment by jdhayhurst** [comment]
transfer team suggest keeping all the original files and just move on from here with a new structure. It would probably be wise to create the new structure and start putting new files in there. For existing files, we could create symlinks. This way we can provide links to the new structure of the ftp.

I would propose the following:

```
summary_statistics
+-- published
|    +-- pmid1
|    |   +-- gcst1
|    |   +-- gcst2
|    +-- pmid2
|    |   +-- gcst3
+-- unpublished
|    +-- gcp1
|    |   +-- gcst4
|    |   +-- gcst5
|    +-- gcp2
|    |   +-- gcst6
+-- gcst...(left to preserve paths)
+-- author_pmid_gcst...(left to preserve paths)
```

**Comment by jdhayhurst** [comment]
For clarification if we had:

```
summary_statistics
+-- author_pmid1_gcst1
+-- author_pmid1_gcst2
```
These would remain but we would add the following structure:

```
summary_statistics
+-- published
|    +-- pmid1
|    |   +-- gcst1 #symlink to author_pmid1_gcst1
|    |   +-- gcst2 #symlink to author_pmid1_gcst2
+-- author_pmid1_gcst1
+-- author_pmid1_gcst2
```

That way we'd have a consistent way to build links e.g. 
if published:
summary_statistics/published/<pmid>/<gcst>
else:
summary_statistics/unpublished/<gcp>/<gcst>

**Comment by ljwh2** [comment]
How would this work for pre-pubs that get PMIDs? I think the original point of linking directly to the GCST was so the submitter had a persistent link that didn't change between pre-pub and PMID state. @JalMacArthur

**Comment by JalMacArthur** [comment]
If you use structure below for everything can you create symlinks if a GCP is assigned a PMID? We talked in past about giving all publications a GCP and using GCP as the primary ID for publication/projects in GWAS Catalog. 
|    +-- gcp1
|    |   +-- gcst4
|    |   +-- gcst5
|    +-- gcp2
|    |   +-- gcst6

**Comment by jdhayhurst** [comment]
@JalMacArthur yes, I prefer your suggestion to use GCP for everything. This would require backfilling the catalog so everything has a GCP. @ljwh2 this will solve your concerns about what happens when an unpub goes to a pub, because the path would not have to change. I think it would look like this:

```
summary_statistics
+-- gcp1
|   +-- gcst1
|   +-- gcst2
+-- gcp2
|   +-- gcst3
+-- gcp3
|   +-- gcst4
|   +-- gcst5
+-- gcp4
|   +-- gcst6
+-- gcst...(left to preserve paths)
+-- author_pmid_gcst...(left to preserve paths)
```

**Comment by jdhayhurst** [comment]
Decision is to make the structure as follows:

summary_statistics
+-- gcst001-gcst002
|   +-- gcst001
|   +-- gcst002
+-- gcst003-gcst004
|   +-- gcst003
|   +-- gcst004
+-- gcst005-gcst006
|   +-- gcst005
+-- gcst...(left to preserve paths)
+-- author_pmid_gcst...(left to preserve paths)

The first-level is a range of gcsts e.g. groups of 1000 gcst000001-gcst001000,  gcst001001-gcst002000. Within, are the gcsts corresponding to that range. This creates arbitrary structure, but users can still navigate in a logical way, which is all that is needed.
